export const assets = [
  {
    symbol: 'BTC',
    name: 'Bitcoin',
    kind: 'Activo nativo',
    network: 'Bitcoin',
    color: '#f7931a',
    use: 'Transferir valor en una red monetaria abierta.',
    mechanism: 'Prueba de trabajo',
    custody: 'Las claves autorizan el gasto de BTC.',
    risk: 'Volatilidad, manejo de claves y comisiones variables.',
    question: '¿Entiendo quién controla las claves y cómo se confirma una operación?',
    source: 'https://bitcoin.org/en/how-it-works',
    mission: '004-bitcoin-sin-ruido',
  },
  {
    symbol: 'ETH',
    name: 'Ethereum',
    kind: 'Activo nativo',
    network: 'Ethereum',
    color: '#a79cff',
    use: 'Pagar ejecución y participar en la seguridad de Ethereum.',
    mechanism: 'Prueba de participación',
    custody: 'Interacciones con contratos y permisos de tokens.',
    risk: 'Volatilidad, contratos, permisos y costos de red.',
    question: '¿La firma mueve fondos o concede permisos a una aplicación?',
    source: 'https://ethereum.org/en/what-is-ethereum/',
    mission: '002-gasolinera-ethereum',
  },
  {
    symbol: 'USDT',
    name: 'Tether',
    kind: 'Stablecoin',
    network: 'Varias redes',
    color: '#50d3b1',
    use: 'Token que busca seguir el valor del dólar estadounidense.',
    mechanism: 'Emisión y reservas de un emisor',
    custody: 'Importan el emisor, la red y el contrato exacto.',
    risk: 'Pérdida de paridad, reservas, restricciones y contraparte.',
    question: '¿Estoy revisando el token y la red correctos, además de las condiciones del emisor?',
    source: 'https://tether.to/en/legal/',
    mission: '005-stablecoins-bajo-la-lupa',
  },
  {
    symbol: 'ADA',
    name: 'Cardano',
    kind: 'Activo nativo',
    network: 'Cardano',
    color: '#4690ff',
    use: 'Activo nativo del ecosistema Cardano.',
    mechanism: 'Prueba de participación',
    custody: 'Distingue la delegación nativa de un servicio custodial.',
    risk: 'Volatilidad, supuestos de uso y condiciones del servicio.',
    question: '¿Delegar significa lo mismo que entregar mis claves a una plataforma?',
    source: 'https://docs.cardano.org/about-cardano/introduction',
    mission: '006-cardano-y-delegacion',
  },
  {
    symbol: 'SOL',
    name: 'Solana',
    kind: 'Activo nativo',
    network: 'Solana',
    color: '#c889ff',
    use: 'Activo nativo utilizado en el ecosistema Solana.',
    mechanism: 'Prueba de participación',
    custody: 'Revisa red, dirección, permisos y aplicaciones.',
    risk: 'Volatilidad, funcionamiento de aplicaciones y seguridad de claves.',
    question: '¿Qué información viene de la red y cuál de la aplicación que utilizo?',
    source: 'https://solana.com/docs',
    mission: '008-mi-primera-tesis',
  },
  {
    symbol: 'USDC',
    name: 'USD Coin',
    kind: 'Stablecoin',
    network: 'Varias redes',
    color: '#66a8ff',
    use: 'Stablecoin de Circle diseñada para seguir el dólar.',
    mechanism: 'Emisión y reservas de un emisor',
    custody: 'Distingue USDC nativo de versiones puenteadas.',
    risk: 'Paridad, emisor, contraparte y puentes cuando apliquen.',
    question: '¿Estoy usando el token nativo o una representación en otra red?',
    source: 'https://www.circle.com/usdc',
    mission: '005-stablecoins-bajo-la-lupa',
  },
];

export const missions = [
  {
    id: '001',
    slug: '001-antes-de-despegar',
    title: 'Antes de despegar',
    track: 'entender',
    topic: 'Fundamentos',
    minutes: 5,
    outcome: 'Distinguir red, activo y precio.',
    deliverable: 'Tu primera pregunta de análisis',
    tool: 'ficha',
    question: '¿Una tecnología útil garantiza que su token suba de precio?',
    options: [
      'Sí, si la red tiene usuarios.',
      'No. Tecnología y precio necesitan análisis separados.',
      'Sólo si es una blockchain conocida.',
    ],
    correct: 1,
    explanation: 'La utilidad de una red no demuestra un rendimiento futuro del activo.',
  },
  {
    id: '004',
    slug: '004-bitcoin-sin-ruido',
    title: 'Bitcoin, sin ruido',
    track: 'entender',
    topic: 'Bitcoin',
    minutes: 6,
    outcome: 'Entender claves, red y confirmaciones.',
    deliverable: 'Ficha de Bitcoin',
    tool: 'ficha',
    asset: 'BTC',
    question: '¿Qué permite autorizar el gasto de bitcoin?',
    options: [
      'Conocer una dirección pública.',
      'Tener una captura del saldo.',
      'Disponer de la clave necesaria para firmar.',
    ],
    correct: 2,
    explanation:
      'Las claves privadas autorizan operaciones. La dirección y el saldo visible no bastan.',
  },
  {
    id: '002',
    slug: '002-gasolinera-ethereum',
    title: 'La gasolinera Ethereum',
    track: 'entender',
    topic: 'Ethereum',
    minutes: 6,
    outcome: 'Separar importe y comisión.',
    deliverable: 'Cálculo de comisión en ETH',
    tool: 'gas',
    asset: 'ETH',
    question: '¿Cuál es la comisión de 21,000 unidades a 10 gwei?',
    options: ['0.00021 ETH.', '0.21 ETH.', '21 ETH.'],
    correct: 0,
    explanation: '21,000 × 10 / 1,000,000,000 = 0.00021 ETH. Es un ejemplo, no una cotización.',
  },
  {
    id: '005',
    slug: '005-stablecoins-bajo-la-lupa',
    title: 'Stablecoins bajo la lupa',
    track: 'entender',
    topic: 'USDT / USDC',
    minutes: 6,
    outcome: 'Identificar emisor, red y paridad.',
    deliverable: 'Comparación USDT / USDC',
    tool: 'comparar',
    asset: 'USDT',
    question: '¿Qué significa que una stablecoin busque valer un dólar?',
    options: [
      'Que no puede perder valor.',
      'Que su objetivo es la paridad, con riesgos que revisar.',
      'Que todos los usuarios pueden canjearla sin condiciones.',
    ],
    correct: 1,
    explanation: 'Un objetivo de paridad no elimina riesgos del emisor, del mercado ni de la red.',
  },
  {
    id: '003',
    slug: '003-la-boveda-cripto',
    title: 'La bóveda cripto',
    track: 'analizar',
    topic: 'Seguridad',
    minutes: 6,
    outcome: 'Reconocer solicitudes de claves y permisos.',
    deliverable: 'Checklist de custodia',
    tool: 'ficha',
    question: 'Soporte te pide la frase semilla por chat. ¿Qué haces?',
    options: [
      'Compartir sólo la mitad.',
      'Enviarla si el logotipo parece oficial.',
      'Detenerme y consultar el canal oficial por otra vía.',
    ],
    correct: 2,
    explanation: 'La frase de recuperación nunca debe compartirse con un supuesto soporte.',
  },
  {
    id: '006',
    slug: '006-cardano-y-delegacion',
    title: 'Cardano: delegar con criterio',
    track: 'analizar',
    topic: 'Cardano',
    minutes: 6,
    outcome: 'Distinguir delegación nativa y custodia.',
    deliverable: 'Ficha de ADA con una duda concreta',
    tool: 'ficha',
    asset: 'ADA',
    question: '¿Delegar ADA y entregar los fondos a un intermediario son equivalentes?',
    options: [
      'No: cambian el control y las condiciones.',
      'Sí: cualquier staking funciona igual.',
      'Sí: siempre hay rentabilidad fija.',
    ],
    correct: 0,
    explanation:
      'Hay que revisar el mecanismo y quién conserva el control, no sólo la palabra staking.',
  },
  {
    id: '007',
    slug: '007-mapa-de-exposicion',
    title: 'Tu mapa de exposición',
    track: 'analizar',
    topic: 'Riesgo',
    minutes: 8,
    outcome: 'Calcular pesos y pérdidas hipotéticas.',
    deliverable: 'Reporte de escenario',
    tool: 'riesgo',
    question: 'Una posición vale $600 de un total de $1,000. ¿Cuál es su peso?',
    options: ['40%.', '60%.', '6%.'],
    correct: 1,
    explanation: '600 / 1,000 × 100 = 60%. El peso cambia cuánto influye una posición en el total.',
  },
  {
    id: '008',
    slug: '008-mi-primera-tesis',
    title: 'Mi primera tesis cripto',
    track: 'documentar',
    topic: 'Análisis',
    minutes: 8,
    outcome: 'Separar hechos, hipótesis e incertidumbre.',
    deliverable: 'Ficha de análisis descargable',
    tool: 'ficha',
    question: '¿Cuál es una tesis que se puede revisar?',
    options: [
      'Va a subir porque lo dice todo el mundo.',
      'Este activo es el futuro.',
      'Mi hipótesis depende de un dato, una fuente y una condición que podría refutarla.',
    ],
    correct: 2,
    explanation: 'Una tesis útil puede contrastarse y cambiar cuando cambia la evidencia.',
  },
  {
    id: '009',
    slug: '009-bitacora-de-decisiones',
    title: 'La bitácora de decisiones',
    track: 'documentar',
    topic: 'Método',
    minutes: 7,
    outcome: 'Registrar una conclusión y cuándo revisarla.',
    deliverable: 'Entrada de bitácora',
    tool: 'bitacora',
    question: '¿Qué hace útil una entrada de bitácora?',
    options: [
      'Fecha, fuente, conclusión y condición de revisión.',
      'Anotar sólo el precio esperado.',
      'Marcar toda noticia como urgente.',
    ],
    correct: 0,
    explanation:
      'La bitácora documenta por qué pensabas algo y qué evidencia justificaría cambiarlo.',
  },
];
export const tracks = [
  {
    id: 'entender',
    title: 'Entender',
    number: '01',
    description: 'Conoce los activos, las redes y sus diferencias. Sin saltarte los fundamentos.',
  },
  {
    id: 'analizar',
    title: 'Analizar',
    number: '02',
    description: 'Lleva las preguntas al laboratorio: custodia, riesgos y exposición.',
  },
  {
    id: 'documentar',
    title: 'Documentar',
    number: '03',
    description: 'Construye una tesis, registra tus conclusiones y vuelve a revisarlas.',
  },
];
