#!/bin/bash

# BitForward - Build Script
# Optimiza y construye la aplicación para producción

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Banner
echo -e "${PURPLE}"
cat << "EOF"
╔══════════════════════════════════════════════════════════╗
║                                                          ║
║   ██████╗ ██╗████████╗███████╗ ██████╗ ██████╗ ██╗    ██║
║   ██╔══██╗██║╚══██╔══╝██╔════╝██╔═══██╗██╔══██╗██║    ██║
║   ██████╔╝██║   ██║   █████╗  ██║   ██║██████╔╝██║ █╗ ██║
║   ██╔══██╗██║   ██║   ██╔══╝  ██║   ██║██╔══██╗██║███╗██║
║   ██████╔╝██║   ██║   ██║     ╚██████╔╝██║  ██║╚███╔███╔╝
║   ╚═════╝ ╚═╝   ╚═╝   ╚═╝      ╚═════╝ ╚═╝  ╚═╝ ╚══╝╚══╝ ║
║                                                          ║
║              Production Build System v3.0               ║
║                    by AFORTU                            ║
╚══════════════════════════════════════════════════════════╝
EOF
echo -e "${NC}"

# Step 1: Clean previous builds
echo -e "${BLUE}[1/7] 🧹 Cleaning previous builds...${NC}"
rm -rf dist
rm -rf dist-legacy
rm -rf .vite
echo -e "${GREEN}✓ Clean completed${NC}\n"

# Step 2: Check dependencies
echo -e "${BLUE}[2/7] 📦 Checking dependencies...${NC}"
if [ ! -d "node_modules" ]; then
    echo -e "${YELLOW}⚠ node_modules not found, running npm install...${NC}"
    npm install
fi
echo -e "${GREEN}✓ Dependencies OK${NC}\n"

# Step 3: Run tests
echo -e "${BLUE}[3/7] 🧪 Running tests...${NC}"
if command -v npm &> /dev/null; then
    npm test -- --passWithNoTests || {
        echo -e "${YELLOW}⚠ Tests failed or not found, continuing...${NC}"
    }
fi
echo -e "${GREEN}✓ Tests completed${NC}\n"

# Step 4: Optimize images
echo -e "${BLUE}[4/7] 🖼️  Optimizing images...${NC}"
if [ -f "scripts/optimize-images.js" ]; then
    node scripts/optimize-images.js || {
        echo -e "${YELLOW}⚠ Image optimization skipped${NC}"
    }
else
    echo -e "${YELLOW}⚠ Image optimizer not found, skipping...${NC}"
fi
echo -e "${GREEN}✓ Image optimization completed${NC}\n"

# Step 5: Build with Vite
echo -e "${BLUE}[5/7] 🏗️  Building application...${NC}"
NODE_ENV=production npm run build

if [ $? -eq 0 ]; then
    echo -e "${GREEN}✓ Build successful${NC}\n"
else
    echo -e "${RED}✗ Build failed${NC}"
    exit 1
fi

# Step 6: Analyze bundle size
echo -e "${BLUE}[6/7] 📊 Analyzing bundle size...${NC}"
if [ -f "dist/stats.html" ]; then
    echo -e "${GREEN}✓ Bundle analysis saved to dist/stats.html${NC}"
    
    # Calculate total size
    TOTAL_SIZE=$(du -sh dist | cut -f1)
    echo -e "${CYAN}📦 Total bundle size: ${TOTAL_SIZE}${NC}"
    
    # Count files
    FILE_COUNT=$(find dist -type f | wc -l)
    echo -e "${CYAN}📄 Total files: ${FILE_COUNT}${NC}"
    
    # Gzip size
    if [ -d "dist/js" ]; then
        GZIP_SIZE=$(find dist/js -name "*.gz" | xargs du -ch | tail -1 | cut -f1)
        echo -e "${CYAN}🗜️  Gzip size: ${GZIP_SIZE}${NC}"
    fi
else
    echo -e "${YELLOW}⚠ Bundle analysis not available${NC}"
fi
echo ""

# Step 7: Generate build report
echo -e "${BLUE}[7/7] 📝 Generating build report...${NC}"
BUILD_TIME=$(date "+%Y-%m-%d %H:%M:%S")
BUILD_HASH=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")

cat > dist/BUILD_INFO.txt << EOF
BitForward - Build Information
================================

Build Time: ${BUILD_TIME}
Git Commit: ${BUILD_HASH}
Node Version: $(node --version)
NPM Version: $(npm --version)

Build Configuration:
- Environment: production
- Minification: Terser
- Compression: Gzip + Brotli
- Tree Shaking: Enabled
- Source Maps: Disabled

Performance Targets:
- Bundle Size: < 250KB (gzipped)
- First Paint: < 0.8s
- Time to Interactive: < 1.5s
- Lighthouse Score: > 95

Bundle Analysis:
- Total Size: ${TOTAL_SIZE}
- File Count: ${FILE_COUNT}
- Gzip Size: ${GZIP_SIZE:-N/A}

Generated by: BitForward Build System v3.0
EOF

echo -e "${GREEN}✓ Build report saved to dist/BUILD_INFO.txt${NC}\n"

# Success banner
echo -e "${GREEN}"
cat << "EOF"
╔══════════════════════════════════════════════════════════╗
║                                                          ║
║                  ✅ BUILD SUCCESSFUL! 🚀                 ║
║                                                          ║
║  Your optimized production build is ready in ./dist     ║
║                                                          ║
║  Next steps:                                            ║
║  • npm run preview - Test production build locally      ║
║  • npm run analyze - View bundle analysis               ║
║  • Deploy to your hosting service                       ║
║                                                          ║
╚══════════════════════════════════════════════════════════╝
EOF
echo -e "${NC}"

# Performance tips
echo -e "${CYAN}💡 Performance Tips:${NC}"
echo -e "  • Enable CDN for static assets"
echo -e "  • Configure HTTP/2 or HTTP/3"
echo -e "  • Set proper cache headers"
echo -e "  • Enable Brotli compression on server"
echo -e "  • Use preconnect for external APIs\n"

echo -e "${PURPLE}🎯 To test the build locally:${NC}"
echo -e "${YELLOW}   npm run preview${NC}\n"

exit 0
